### ISSUE TITLE
Net7 needed in Net8 project?

### ISSUE THREAD

**Issue by btammenga** [HenkKin/EntityCloner.Microsoft.EntityFrameworkCore#12]
We published our Net8 project to IIS. But are running into a problem with the EntityCloner.
On our IIS Net6 and Net8 are installed.
On our Dev machines with also Net7 present it's working fine.

The error is:
`System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable'1<Microsoft.EntityFrameworkCore.Metadata.IReadOnlyProperty> Microsoft.EntityFrameworkCore.Metadata.IReadOnlyEntityType.GetProperties()'.
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.ResetEntityProperties(DbContext source, Object entity, String definingNavigationName, IReadOnlyEntityType definingEntityType, Object clonedEntity)
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.InternalClone(DbContext source, Object entity, String definingNavigationName, IReadOnlyEntityType definingEntityType, Dictionary'2 references)
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.CloneAsync[TEntity](DbContext source, Func'2 includeQuery, Object[] primaryKey)`

**Comment by HenkKin** [comment]
OK will investigate

**Comment by HenkKin** [comment]
I can not reproduce it

**Comment by btammenga** [comment]
> I can not reproduce it

Thanks for your time.
Perhaps removing the Net7 support and leaving only LTS Net6 and Net8, would help?
Our solution is working for us.
